-- =============================================
-- MIGRATION: Add Shipping Methods and Update Orders
-- Run this on your existing Supabase database
-- =============================================

-- 1. Create shipping_methods table
CREATE TABLE IF NOT EXISTS shipping_methods (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  estimated_days TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Insert default shipping methods
INSERT INTO shipping_methods (name, description, price, estimated_days) VALUES
  ('Estandar', 'Entrega en 3-5 dias laborables', 0, '3-5 dias'),
  ('Express', 'Entrega en 24-48 horas', 4.99, '24-48h')
ON CONFLICT DO NOTHING;

-- 3. Add shipping_method_id column to orders (nullable to preserve existing orders)
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS shipping_method_id INTEGER REFERENCES shipping_methods(id);

-- 4. Add order_number column if it doesn't exist (for display purposes)
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 5. Create index for shipping_method_id
CREATE INDEX IF NOT EXISTS idx_orders_shipping_method ON orders(shipping_method_id);

-- =============================================
-- NOTE: orders.id remains as UUID to preserve existing data
-- The order_number column provides a human-readable sequential number
-- =============================================
