-- =============================================
-- FashionMarket Database Schema (Mejorado)
-- Ejecutar en Supabase SQL Editor
-- =============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- 📦 TABLA: categories
-- =============================================
CREATE TABLE IF NOT EXISTS categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Categorías por defecto
INSERT INTO categories (name, slug) VALUES
  ('Camisas', 'camisas'),
  ('Pantalones', 'pantalones'),
  ('Trajes', 'trajes');

-- =============================================
-- 👕 TABLA: products
-- =============================================
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
  is_offer BOOLEAN DEFAULT FALSE,
  sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL'],
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  original_price NUMERIC(10, 2),
  discount_percent INTEGER CHECK (discount_percent >= 0 AND discount_percent <= 100)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_is_offer ON products(is_offer) WHERE is_offer = TRUE;

-- =============================================
-- 🖼️ TABLA: product_images
-- Relación 1:N con products
-- Almacena URLs de imágenes (Cloudinary, etc.)
-- =============================================
CREATE TABLE IF NOT EXISTS product_images (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL, -- URL completa de la imagen (ej: Cloudinary)
  "order" INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  color VARCHAR(100),
  color_hex VARCHAR(20)
);

-- Índice para obtener imágenes de un producto ordenadas
CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images(product_id, "order");

-- =============================================
-- =============================================
-- TABLA: shipping_methods
-- Metodos de envio disponibles
-- =============================================
CREATE TABLE IF NOT EXISTS shipping_methods (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  estimated_days TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Metodos de envio por defecto
INSERT INTO shipping_methods (name, description, price, estimated_days) VALUES
  ('Estandar', 'Entrega en 3-5 dias laborables', 0, '3-5 dias'),
  ('Express', 'Entrega en 24-48 horas', 4.99, '24-48h')
ON CONFLICT DO NOTHING;

-- =============================================
-- TABLA: orders
-- =============================================
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS facturacion CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  order_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  total_price NUMERIC(10, 2) NOT NULL CHECK (total_price >= 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')),
  customer_email TEXT,
  customer_name TEXT,
  shipping_address TEXT,
  shipping_method_id INTEGER REFERENCES shipping_methods(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices para orders
CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at DESC);

-- =============================================
-- TABLA: order_items
-- Detalle de cada pedido
-- =============================================
CREATE TABLE order_items (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  size TEXT,
  price_at_purchase NUMERIC(10, 2) NOT NULL CHECK (price_at_purchase >= 0),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indice
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);

-- =============================================
-- ⚙️ TABLA: settings
-- Configuración global del sistema
-- =============================================
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT 'false',
  description TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Configuración inicial
INSERT INTO settings (key, value, description) VALUES
  ('offers_enabled', 'true', 'Habilitar sección de Ofertas Flash'),
  ('free_shipping_threshold', '5000', 'Mínimo para envío gratis (en céntimos)'),
  ('store_open', 'true', 'Tienda abierta para pedidos');

-- =============================================
-- 🏷️ TABLA: tags
-- Etiquetas para productos (colores, estilos, etc.)
-- =============================================
CREATE TABLE IF NOT EXISTS tags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(100) NOT NULL UNIQUE,
  type VARCHAR(50) DEFAULT 'general'
);

-- Índice
CREATE INDEX IF NOT EXISTS idx_tags_type ON tags(type);
CREATE INDEX IF NOT EXISTS idx_tags_slug ON tags(slug);

-- =============================================
-- 🔗 TABLA: product_tags
-- Relación N:M entre productos y etiquetas
-- =============================================
CREATE TABLE IF NOT EXISTS product_tags (
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (product_id, tag_id)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_product_tags_product ON product_tags(product_id);
CREATE INDEX IF NOT EXISTS idx_product_tags_tag ON product_tags(tag_id);

-- =============================================
-- 📏 TABLA: product_variants
-- Variantes de talla/stock por producto
-- =============================================
CREATE TABLE IF NOT EXISTS product_variants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  size VARCHAR(20) NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  sku VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_variants_unique ON product_variants(product_id, size);
CREATE INDEX IF NOT EXISTS idx_product_variants_product ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_sku ON product_variants(sku) WHERE sku IS NOT NULL;

-- =============================================
-- 🔄 TRIGGER: updated_at automático
-- =============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_settings_updated_at
  BEFORE UPDATE ON settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================
-- 🔒 ROW LEVEL SECURITY (RLS)
-- =============================================

-- Habilitar RLS
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;

-- ----- CATEGORIES -----
-- Lectura pública
CREATE POLICY "categories_public_read"
  ON categories FOR SELECT
  TO public
  USING (true);

-- Escritura: solo usuarios autenticados con verificación explícita
CREATE POLICY "categories_auth_write"
  ON categories FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- ----- PRODUCTS -----
-- Lectura pública (solo activos)
CREATE POLICY "products_public_read"
  ON products FOR SELECT
  TO public
  USING (active = true);

-- Escritura: solo usuarios autenticados
CREATE POLICY "products_auth_write"
  ON products FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- ----- PRODUCT_IMAGES -----
-- Lectura pública (si el producto está activo)
CREATE POLICY "product_images_public_read"
  ON product_images FOR SELECT
  TO public
  USING (
    EXISTS (
      SELECT 1 FROM products 
      WHERE products.id = product_images.product_id 
      AND products.active = true
    )
  );

-- Escritura: solo usuarios autenticados
CREATE POLICY "product_images_auth_write"
  ON product_images FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- ----- ORDERS -----
-- Lectura y gestión: solo usuarios autenticados
CREATE POLICY "orders_auth_all"
  ON orders FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- Inserción anónima: solo permitir crear pedidos con campos válidos
CREATE POLICY "orders_anon_insert"
  ON orders FOR INSERT
  TO anon
  WITH CHECK (
    total_price >= 0 
    AND status = 'pending'
  );

-- ----- ORDER_ITEMS -----
-- Lectura y gestión: solo usuarios autenticados
CREATE POLICY "order_items_auth_all"
  ON order_items FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- Inserción anónima: validar que el item tiene datos correctos
CREATE POLICY "order_items_anon_insert"
  ON order_items FOR INSERT
  TO anon
  WITH CHECK (
    quantity > 0 
    AND price_at_purchase >= 0
  );

-- ----- SETTINGS -----
-- Lectura pública (para configuración del frontend)
CREATE POLICY "settings_public_read"
  ON settings FOR SELECT
  TO public
  USING (true);

-- Escritura: solo usuarios autenticados
CREATE POLICY "settings_auth_write"
  ON settings FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- ----- TAGS -----
-- Lectura pública
CREATE POLICY "tags_public_read"
  ON tags FOR SELECT
  TO public
  USING (true);

-- Escritura: solo usuarios autenticados
CREATE POLICY "tags_auth_write"
  ON tags FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- ----- PRODUCT_TAGS -----
-- Lectura pública (si el producto está activo)
CREATE POLICY "product_tags_public_read"
  ON product_tags FOR SELECT
  TO public
  USING (
    EXISTS (
      SELECT 1 FROM products 
      WHERE products.id = product_tags.product_id 
      AND products.active = true
    )
  );

-- Escritura: solo usuarios autenticados
CREATE POLICY "product_tags_auth_write"
  ON product_tags FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- ----- PRODUCT_VARIANTS -----
-- Lectura pública (si el producto está activo)
CREATE POLICY "product_variants_public_read"
  ON product_variants FOR SELECT
  TO public
  USING (
    EXISTS (
      SELECT 1 FROM products 
      WHERE products.id = product_variants.product_id 
      AND products.active = true
    )
  );

-- Escritura: solo usuarios autenticados
CREATE POLICY "product_variants_auth_write"
  ON product_variants FOR ALL
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- =============================================
-- 📸 IMÁGENES
-- =============================================
-- ⚠️  Las imágenes se almacenan en Cloudinary (o servicio externo)
-- ⚠️  NO se usa Supabase Storage
-- ⚠️  La tabla product_images almacena las URLs completas
-- =============================================

-- =============================================
-- 🧪 DATOS DE PRUEBA (Opcional)
-- =============================================

-- Productos de ejemplo
INSERT INTO products (name, slug, description, price, stock, category_id, is_offer) VALUES
  (
    'Camisa Oxford Premium',
    'camisa-oxford-premium',
    'Camisa Oxford de algodón 100% con acabado premium. Perfecta para ocasiones formales e informales.',
    89.99,
    25,
    (SELECT id FROM categories WHERE slug = 'camisas'),
    false
  ),
  (
    'Pantalón Chino Slim',
    'pantalon-chino-slim',
    'Pantalón chino de corte slim en algodón elástico. Comodidad y elegancia en un solo producto.',
    74.99,
    30,
    (SELECT id FROM categories WHERE slug = 'pantalones'),
    true
  ),
  (
    'Traje Ejecutivo Marino',
    'traje-ejecutivo-marino',
    'Traje de dos piezas en lana italiana. El epítome de la elegancia masculina.',
    349.99,
    10,
    (SELECT id FROM categories WHERE slug = 'trajes'),
    false
  );

-- Imágenes de los productos
INSERT INTO product_images (product_id, image_url, "order") VALUES
  ((SELECT id FROM products WHERE slug = 'camisa-oxford-premium'), 'https://placehold.co/800x1000/1e3a5f/ffffff?text=Oxford+1', 0),
  ((SELECT id FROM products WHERE slug = 'camisa-oxford-premium'), 'https://placehold.co/800x1000/1e3a5f/ffffff?text=Oxford+2', 1),
  ((SELECT id FROM products WHERE slug = 'pantalon-chino-slim'), 'https://placehold.co/800x1000/374151/ffffff?text=Chino+1', 0),
  ((SELECT id FROM products WHERE slug = 'traje-ejecutivo-marino'), 'https://placehold.co/800x1000/1e3a5f/ffffff?text=Traje+1', 0),
  ((SELECT id FROM products WHERE slug = 'traje-ejecutivo-marino'), 'https://placehold.co/800x1000/1e3a5f/ffffff?text=Traje+2', 1);

-- =============================================
-- 📊 VISTAS ÚTILES (Opcional)
-- =============================================

-- Vista de productos con su imagen principal
-- Usamos SECURITY INVOKER para respetar RLS del usuario que consulta
CREATE OR REPLACE VIEW products_with_image 
WITH (security_invoker = true) AS
SELECT 
  p.*,
  c.name as category_name,
  c.slug as category_slug,
  (
    SELECT image_url 
    FROM product_images pi 
    WHERE pi.product_id = p.id 
    ORDER BY pi."order" ASC 
    LIMIT 1
  ) as main_image
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.active = true;

ALTER TABLE carousel_slides ADD COLUMN IF NOT EXISTS discount_code TEXT;
ALTER TABLE carousel_slides ADD COLUMN IF NOT EXISTS style_config JSONB DEFAULT '{}'::jsonb;

-- =============================================
-- TABLA: facturacion
-- Facturas generadas a partir de pedidos
-- =============================================
DROP TABLE IF EXISTS facturacion;

CREATE TABLE facturacion (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_order_facturacion UNIQUE (order_id)
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_facturacion_order_id ON facturacion(order_id);

-- RLS Policies
ALTER TABLE facturacion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view all facturacion" ON facturacion;
CREATE POLICY "Admins can view all facturacion" 
ON facturacion FOR SELECT 
USING (auth.role() = 'service_role' OR EXISTS (
  SELECT 1 FROM admins WHERE email = auth.email()
));

DROP POLICY IF EXISTS "Admins can insert facturacion" ON facturacion;
CREATE POLICY "Admins can insert facturacion" 
ON facturacion FOR INSERT 
WITH CHECK (auth.role() = 'service_role' OR EXISTS (
  SELECT 1 FROM admins WHERE email = auth.email()
));

DROP POLICY IF EXISTS "Admins can update facturacion" ON facturacion;
CREATE POLICY "Admins can update facturacion" 
ON facturacion FOR UPDATE 
USING (auth.role() = 'service_role' OR EXISTS (
  SELECT 1 FROM admins WHERE email = auth.email()
));

-- =============================================
-- 🆕 UPDATE: Precios por talla (Requiere migración)
-- =============================================
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) DEFAULT NULL;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS is_offer BOOLEAN DEFAULT FALSE;

